---
all:
  children:

    docker_hosts:

      hosts:

        debian-dev:

          ansible_host: 192.168.1.34

    k3s_cluster:

      children:

        k3s_server:

          hosts:

            k3s-server:

              ansible_host: 192.168.1.58

        k3s_agent:

          hosts:

            k3s-agent:

              ansible_host: 192.168.1.63
