name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  markdown:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v20

  yaml:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: ibiqlik/action-yamllint@v3